application: handy-resolver-113719
version: 2
runtime: go
api_version: go1

default_expiration: 1d

handlers:
- url: /admin.*
  script: _go_app
  login: admin
  secure: optional

- url: .*
  script: _go_app
  secure: optional
